version: "3"

services:
  etcd1:
    image: bitnami/etcd:3.5.1
    container_name: etcd1
    # restart: always
    networks:
      - etcd-net
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      # - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ROOT_PASSWORD=etcd1
    volumes:
      - etcd1_data:/bitnami/etcd

  etcd2:
    image: bitnami/etcd:3.5.1
    container_name: etcd2
    # restart: always
    networks:
      - etcd-net
    ports:
      - 23792:2379
      - 23802:2380
    environment:
      # - ALLOW_NONE_AUTHENTICATION=true
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ROOT_PASSWORD=etcd2
    volumes:
      - etcd2_data:/bitnami/etcd

  etcd3:
    image: bitnami/etcd:3.5.1
    container_name: etcd3
    # restart: always
    networks:
      - etcd-net
    ports:
      - 23793:2379
      - 23803:2380
    environment:
      # - ALLOW_NONE_AUTHENTICATION=true
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ROOT_PASSWORD=etcd3
    volumes:
      - etcd3_data:/bitnami/etcd

  etcd-gate:
    image: ifisjayj/etcdgate:0.0.1
    container_name: etcd-gate
    # restart: always
    ports:
      - 8080:8080
    networks:
      - etcd-net
    environment:
      - ADDR=http://etcd1:2379       # etcd address
      - PORT=8080                    # etcd-gate listen port
      - AUTH=true                    # enable auth
      - ROOT=root                    # default root username
      - PWD=root                     # default root password
      - TIMEOUT=5                    # timeout per request
      - TLS=false                    # enable tls
      - CA=                          #
      - CERT=                        #
      - KEYFILE=                     #
      - SEPARATOR=/                  # root separator
      - GIN_MODE=release             # gin mode, set debug to debug
networks:
  etcd-net:
    driver: bridge

volumes:
  etcd1_data:
    driver: local
  etcd2_data:
    driver: local
  etcd3_data:
    driver: local